/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Referee.java
 *
 * Created on 17 avr. 2012, 17:38:10
 */
package debate.gui;

import debate.game.Player;
import debate.game.Referee;
import debate.gui.renderer.ListCellRendererForFormula;
import debate.gui.renderer.TreeCellRendererForArgument;
import debate.logical.Argument;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import satoulouse.Formula;

/**
 *
 * @author Propriétaire
 */


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
public class RefereePane extends javax.swing.JPanel {

    private Referee referee;

    /** Creates new form Referee */
    public RefereePane() {
        initComponents();
        referee=null;
        current_score=50;
    }

    public JButton getNewGameButton() {
        return newGameJButton;
    }

    public void newReferee() {
        referee = new Referee();
    }
    
    //Nouvel arbitre après restauration
     int newReferee(ArrayList<String> socle) {
         boolean continu=true;
         ArrayList<String> topics=new ArrayList<>();
         int count=0;
         boolean sound=false;
         
         if (socle.size() > 2){/*Alors chargement d'une partie*/
            for (int i=0; continu; i++)
            {
                if (Character.isDigit(socle.get(i+2).charAt(0)))
                {
                    count--;
                    continu=false;
                }
                else
                    topics.add(socle.get(i+2));
                count++;
            }
         }
       
         if (socle.get(0).contentEquals("Sound enabled"))
             sound=true;
            referee=new Referee(topics, sound, Integer.parseInt(socle.get(1)));
         return (count);
     }              
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGameJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        formulasJList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTreeArguments = new javax.swing.JTree();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Referee", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        newGameJButton.setText("New game");
        newGameJButton.setName("newGameJButton"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        formulasJList.setBorder(javax.swing.BorderFactory.createTitledBorder("Common Formulas"));
        formulasJList.setModel(new DefaultListModel());
        formulasJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        formulasJList.setCellRenderer(new ListCellRendererForFormula());
        formulasJList.setFocusable(false);
        formulasJList.setName("formulasJList"); // NOI18N
        formulasJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                formulasJListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(formulasJList);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Request Legend"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_blue.png"))); // NOI18N
        jLabel1.setText("Assert");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_green.png"))); // NOI18N
        jLabel2.setText("Argue");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_pink.png"))); // NOI18N
        jLabel3.setText("Challenge");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_yellow.png"))); // NOI18N
        jLabel4.setText("Quiz");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_bluesky.png"))); // NOI18N
        jLabel5.setText("QuizLink");
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTreeArguments.setBorder(javax.swing.BorderFactory.createTitledBorder("Arguments"));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeArguments.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeArguments.setCellRenderer(new TreeCellRendererForArgument());
        jTreeArguments.setFocusable(false);
        jTreeArguments.setName("jTreeArguments"); // NOI18N
        jTreeArguments.setRootVisible(false);
        jScrollPane2.setViewportView(jTreeArguments);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/raquette2.png"))); // NOI18N
        jLabel6.setName("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/raquette.png"))); // NOI18N
        jLabel7.setName("jLabel7");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tennis50.png"))); // NOI18N
        jLabel10.setName("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(newGameJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newGameJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formulasJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_formulasJListValueChanged
        // TODO add your handling code here:
    formulasJList.setSelectedIndex(-1);
    formulasJList.setFocusable(false);
    }//GEN-LAST:event_formulasJListValueChanged

  public JTree getArgumentsTree() {
        return jTreeArguments;
    }

    public JList getFormulasJList() {
        return formulasJList;
    }

    public Referee getReferee() {
        return referee;
    }
    
    public boolean soundEnabled(){
        return referee.getSound();
    }

    public void refreshModel() {
        ((DefaultListModel) formulasJList.getModel()).clear();
        for (String s : referee.getFormulaList()) {
            ((DefaultListModel) formulasJList.getModel()).addElement(s);
        }
        refreshArgumentTree();
    }

    private void refreshArgumentTree() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Argument List");
        for (Argument arg : referee.getArgumentList()) {
            DefaultMutableTreeNode argumentNode = new DefaultMutableTreeNode(arg);
            for (Formula f : arg.getSupport()) {
                argumentNode.add(new DefaultMutableTreeNode(f));
            }
            root.add(argumentNode);
        }
        ((DefaultTreeModel) jTreeArguments.getModel()).setRoot(root);
    }

    public int refreshScore(Player p1, Player p2) {   
        int score=referee.calculateScore(p1, p2);
        jLabel10.setToolTipText(score+"");
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/icons/tennis"+score+".png")));
        this.current_score=score;
        return (score);
    }
    
    public int getScore(){
        return current_score;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList formulasJList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTreeArguments;
    private javax.swing.JButton newGameJButton;
    // End of variables declaration//GEN-END:variables
    private int current_score;
   
}
