/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestForListPanel.java
 *
 * Created on 9 mai 2012, 13:26:12
 */
package debate.gui.renderer;

import javax.swing.ImageIcon;
import satoulouse.FormulaLabel;

/**
 *
 * @author julien
 */
public class RequestForListPanel extends javax.swing.JPanel {

    /** Creates new form RequestForListPanel */
    public RequestForListPanel() {
        initComponents();
    }
    
    /** Create a panel with the right icon color and formula **/
    public RequestForListPanel (ImageIcon colorIcon, FormulaLabel formula) {
        coloredIcon.setIcon(colorIcon);
        formulaIcon = formula ;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coloredIcon = new javax.swing.JLabel();
        formulaIcon = new javax.swing.JLabel();

        setOpaque(false);

        coloredIcon.setText("Formule");

        formulaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_blue.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formulaIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coloredIcon)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formulaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(coloredIcon)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coloredIcon;
    private javax.swing.JLabel formulaIcon;
    // End of variables declaration//GEN-END:variables
}
