/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MovePaneNew.java
 *
 * Created on 9 mai 2012, 23:37:59
 */
package debate.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author julien
 */
public class MovesPane extends javax.swing.JPanel {

    /** Creates new form MovePaneNew */
    public MovesPane() {
        initComponents();
        buttonlist = new ArrayList<>();
        buttonlist.add(acceptButton);
        buttonlist.add(argueButton);
        buttonlist.add(assertButton);
        buttonlist.add(challengeButton);
        buttonlist.add(closeButton);
        buttonlist.add(dismantleButton);
        buttonlist.add(quizButton);
        buttonlist.add(quizLinkButton);
        buttonlist.add(replaceButton);
        buttonlist.add(agreeButton);
        buttonlist.add(retractButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assertButton = new javax.swing.JButton();
        argueButton = new javax.swing.JButton();
        dismantleButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        agreeButton = new javax.swing.JButton();
        challengeButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();
        quizButton = new javax.swing.JButton();
        quizLinkButton = new javax.swing.JButton();
        retractButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 0));

        assertButton.setText("Assert");
        add(assertButton);

        argueButton.setText("Argue");
        add(argueButton);

        dismantleButton.setText("Dismantle");
        add(dismantleButton);

        acceptButton.setText("Accept");
        add(acceptButton);

        agreeButton.setText("Agree");
        add(agreeButton);

        challengeButton.setText("Challenge");
        add(challengeButton);

        replaceButton.setText("Replace");
        add(replaceButton);

        quizButton.setText("Quiz");
        add(quizButton);

        quizLinkButton.setText("Quiz Link");
        add(quizLinkButton);

        retractButton.setText("Retract");
        add(retractButton);

        closeButton.setText("Close");
        add(closeButton);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton agreeButton;
    private javax.swing.JButton argueButton;
    private javax.swing.JButton assertButton;
    private javax.swing.JButton challengeButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton dismantleButton;
    private javax.swing.JButton quizButton;
    private javax.swing.JButton quizLinkButton;
    private javax.swing.JButton replaceButton;
    private javax.swing.JButton retractButton;
    // End of variables declaration//GEN-END:variables
    private List<JButton> buttonlist;

    public JButton getAcceptButton() {
        return acceptButton;
    }

    public JButton getAgreeButton() {
        return agreeButton;
    }

    public JButton getArgueButton() {
        return argueButton;
    }

    public JButton getAssertButton() {
        return assertButton;
    }

    public List<JButton> getButtonlist() {
        return buttonlist;
    }

    public JButton getChallengeButton() {
        return challengeButton;
    }

    public JButton getCloseButton() {
        return closeButton;
    }

    public JButton getDismantleButton() {
        return dismantleButton;
    }

    public JButton getQuizButton() {
        return quizButton;
    }

    public JButton getQuizLinkButton() {
        return quizLinkButton;
    }

    public JButton getReplaceButton() {
        return replaceButton;
    }

    public JButton getRetractButton() {
        return retractButton;
    }

    public void activateAllButton(boolean status) {
        for (JButton b : buttonlist) {
            b.setEnabled(status);
        }
    }
    

    
    
}
